[package]
name = "product-config"
version = "0.1.0"
authors = ["Malte Sander <malte.sander.it@gmail.com>"]
edition = "2018"
description = "A library to read and validate a product configuration"
license = "Apache License 2.0"

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
regex = "1.0"
thiserror = "1.0"
semver = "0.11"

[dev-dependencies]
rstest = "0.6"

