[package]
authors = ["Malte Sander <malte.sander.it@gmail.com>"]
description = "A library to read and validate a product configuration"
edition = "2018"
license = "Apache-2.0"
name = "product-config"
version = "0.1.0-nightly"

[dependencies]
regex = "1"
semver = "0.11"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
thiserror = "1"

[dev-dependencies]
rstest = "0.10"
